FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom config
COPY frontend/nginx.conf /etc/nginx/conf.d/

# Copy frontend assets
COPY frontend/ /usr/share/nginx/html/
